### ISSUE TITLE
Page contents link location

### ISSUE THREAD

**Issue by rob-at-cortex** [AirWalk-Digital/airview-next#40] opened 2024-07-02 19:04 UTC
when navigating to page contents i.e. /docs/view/default/solutions/copilot_solutions_lvweslp2/_index.md#copilot-studio-formerly-power-virtual-agents

the title of the section being linked is hidden above the top banner

**Comment by f-steel** [comment] 2024-07-05 08:50
it appears that we are using the MDXContent component to create the page content. h2's and h3's etc are created by this and the relevant id's are added to the tags so that the links can be anchored. The problem is that it's slightly off, probably due to some css elsewhere. A solution could be to apply custom css (something like `scroll-margin-top: 20px`) to the MDXContent so it navigates to the correct place

**Comment by f-steel** [comment] 2024-07-05 15:16
found this pretty tricky so far. Seems like a lot of the functionality is hidden away via the component so may need to find out if part of the css is causing the offset and fix it from there

**Comment by rob-at-cortex** [comment] 2024-07-08 21:07
recon this is the same issue as the collaborative editor ?

**Comment by f-steel** [comment] 2024-07-09 14:36
<strike> https://github.com/AirWalk-Digital/airview-next/pull/53 fix for the issue </strike>
now merged

**Closed as completed** 2024-07-10 10:00 UTC
